version: "3"
services:
  back:
    image: mern-back
    ports:
      - 4000:4000
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - type: volume
      source: mongodb
      target: /data/db
  front:
    image: localhost:5000/mern-front
    ports:
      - 8000:80
volumes:
  mongodb:
